apiVersion: v1
kind: Secret
metadata:
  name: dcsdcds43144534534563-secret
  namespace: dcsdcds43144534534563
type: Opaque
data:
  rootpassword: ${{secret.ROOTPASSWORD}} | base64
  userpassword: ${{secret.USERPASSWORD}} | base64
